function [varargout] = ideal_sigs(ph, pl)
  [varargout{1:nargout}] = brigid.load_signals(ph, pl,...
    brigid.p.changeClass(@single),...
    brigid.p.smooth(),...
    brigid.p.frequency_range(2e9, 4e9),...
    brigid.p.do_subtraction(),...
    brigid.p.multi(),...
    brigid.p.fold_reciprocal(@mean)...
    );
end
