function [varargout] = raw_sigs(ph, pl)
  %% [fd, fa, chs] = raw_sigs(ph, pl);
  [varargout{1:nargout}] = brigid.load_signals(ph, pl,...
    brigid.p.changeClass(@single),...
    brigid.p.smooth(),...
    brigid.p.frequency_range(2e9, 4e9),...
    brigid.p.rotat_chs(),...
    brigid.p.fold_reciprocal(@mean)...
    );
end
