function [varargout] = rotat_sigs(ph, pl)
  %% [fd, fa, chs] = rotat_sigs(ph, pl);
  [varargout{1:nargout}] = brigid.load_signals(ph, pl,...
    brigid.p.changeClass(@single),...
    brigid.p.smooth(),...
    brigid.p.frequency_range(2e9, 4e9),...
    brigid.p.rotat(),...
    brigid.p.do_subtraction(),...
    brigid.p.fold_reciprocal(@mean)...
    );
end
