function [varargout] = rotat_raw_sigs(ph, pl)
  %% [fd, fa, chs] = rotat_raw_sigs(ph, pl);
  [varargout{1:nargout}] = brigid.load_signals(ph, pl,...
    brigid.p.changeClass(@single),...
    brigid.p.smooth(),...
    brigid.p.frequency_range(1.5e9, 4.5e9),...
    brigid.p.rotat(),...
    brigid.p.fold_reciprocal(@mean)...
    );
end
